name: The Chew Lab @ Genome Institute of Singapore
url: https://chewlab.github.io
description: The Chew Lab

permalink: /themes/:Spectral/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
